apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  namespace: blob-api
  labels:
    app: node-api
spec:
  type: ClusterIP
  selector:
    app: node-api
  ports:
    - name: http
      port: 80 # internal service port
      targetPort: 3000 # container port
