name: Build Server Image

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server-image-build.yml"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hemanthrasabhathula/best-lines-of-books-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for arm64 build)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: YOUR_USERNAME/best-lines-of-books-gitops
          path: gitops
          token: ${{ secrets.GH_PAT }}

      - name: Update Deployment Image Tag
        run: |
          sed -i "s|image:.*|image: ${IMAGE_NAME}:${{ github.sha }}|" \
            gitops/environments/dev/blob-app-deployment.yaml

      - name: Commit & Push GitOps update
        run: |
          cd gitops
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "deploy: update backend image to ${{ github.sha }}"
          git push
